[package]
name = "aptosforo"
version = "1.0.0"
authors = []

[addresses]
# aptosforo_addr          = '_'
# escalation_manager_addr = '_'
# treasury_addr           = '_'
aptosforo_addr          = '0x96a85483670ce99043549ff9e11ed9f5219861e1733eb4cb2f1959c2ac6bab31'
escalation_manager_addr = '0x96a85483670ce99043549ff9e11ed9f5219861e1733eb4cb2f1959c2ac6bab31'
treasury_addr           = '0x96a85483670ce99043549ff9e11ed9f5219861e1733eb4cb2f1959c2ac6bab31'

[dev-addresses]
# aptosforo_addr          = '0x111'
# escalation_manager_addr = '0x222'
# treasury_addr           = '0x333'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]